apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: qq3
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/d/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: qq3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
