apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-podpvc
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
  namespace: qq2
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: pvc-volume
      readOnly: true
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: podpvc
