apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: false
parameters:
  type: gp2
