apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: qq2
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "while true; do echo 'Hello from Alpine'; sleep 10; done"]
